repos:
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.8.0
  hooks:
  - id: mypy
    additional_dependencies:
    - importlib_resources
    - lxml-stubs
    - nbclient
    - pint
    - pytest
    - sdmx1
    - Sphinx
    - types-PyYAML
    - types-pytz
    - types-python-dateutil
    - types-requests
    - xarray
    args: []
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.2.1
  hooks:
  - id: ruff
  - id: ruff-format
    args: [ --check ]
