name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    uses: iiasa/actions/.github/workflows/lint.yaml@main
    with:
      # If the "Latest version testable on GitHub Actions" in pytest.yaml
      # is not the latest 3.x stable version, adjust here to match:
      python-version: "3.10"
      type-hint-packages: pytest ixmp types-PyYAML types-setuptools xarray
