name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    uses: iiasa/actions/.github/workflows/lint.yaml@main
    with:
      # If the "Latest version testable on GitHub Actions" in pytest.yaml
      # is not the latest 3.x stable version, adjust here to match:
      python-version: "3.10"
      type-hint-packages: >-
        importlib_resources
        nbclient
        "pint < 0.21"
        pytest
        types-PyYAML
        xarray
